/*
-username : Andreea
-password : 1234
*/


CREATE TABLE utenti(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nome VARCHAR(256),
	cognome VARCHAR(256),
	email VARCHAR(256) UNIQUE,
	password VARCHAR(256) NOT NULL,
	frasePresentazione VARCHAR(256),
	urlProfilo VARCHAR(256),
	dataNascita DATE
)

CREATE TABLE gruppi(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	nome VARCHAR(256),
	urlImmagine VARCHAR(256)
	amministratore INTEGER
)

CREATE TABLE postType (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32)
);

CREATE TABLE post(
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	autore INTEGER,
	contenuto VARCHAR(1024),
	allegato VARCHAR(256),
	tipo INTEGER,
	idGroup INTEGER,
	idUser INTEGER,
	FOREIGN KEY (tipo) REFERENCES postType(id),
	FOREIGN KEY (idGroup) REFERENCES gruppi(id),
	FOREIGN KEY (idUser) REFERENCES utenti((id)
}

CREATE TABLE iscrizioni(
	idGruppi INTEGER,
	idUtenti INTEGER,
	FOREIGN KEY (idGroup) REFERENCES gruppi(id),
	FOREIGN KEY (idUser) REFERENCES utenti((id)
	
)

CREATE TABLE amicizie(
	idUtente1 INTEGER,
	idUtente2 INTEGER,
	FOREIGN KEY(idUtente1) REFERENCES utenti(id),
	FOREIGN KEY(idUtente2) REFERENCES utenti(id)	
)

/*
Inserimento dei tre utenti
*/
INSERT INTO utenti (id, nome, cognome,password, frasePresentazione,urlProfilo, dataNascita) 
VALUES (default,
		'Bugs'
		'Bunny'
		'123'
		'Ho le orecchie più belle del mondo'
		'img/bunny.jpg'
		'27/07/1940'
		);
		
INSERT INTO utenti (id, nome, cognome,password, frasePresentazione,urlProfilo, dataNascita) 
VALUES (default,
		'Deadpool'
		''
		'456'
		''
		'img/images.jpg'
		'07/02/1991'
		);

INSERT INTO utenti (id, nome, cognome,password, frasePresentazione,urlProfilo, dataNascita) 
VALUES (default,
		'Jerry'
		''
		'789'
		'img/images1.jpg'
		'Sono un topo obbediente'
		'01/01/1940'
		);
		
/*
Inserimento dei due gruppi
*/

INSERT INTO gruppi(id, nome, urlImmagine ,amministratore)
VALUES (default
		'CartoonNetwork'
		'img/cn.png'
		);
		
INSERT INTO gruppi(id, nome, urlImmagine ,amministratore)
VALUES (default
		'Marvel'
		'img/marvel.jpg'
		);


/*
Inserimento dei  tipi di post
*/
INSERT INTO postType(id, nome)
VALUES (default,
		'TEXT'
);

INSERT INTO postType(id, nome)
VALUES (default
		'IMAGE'
);


INSERT INTO postType(id, nome)
VALUES (default
		'LINK'
);
		
/*
Inserimento dei  post
*/
		
INSERT INTO post(id, autore,contenuto ,allegato, tipo, idGroup, idUser )
VALUES (default,
		'0'
		'Un sondaggio inglese rivela: la frase più ricordata tra gli amanti dei cartoon è quella del celebre coniglio: «Che succede amico?»Bugs Bunny Per gli americani dev\'essere una sorta di riflesso condizionato: davanti alle orecchie di un coniglio viene automatico pensare «what\'s up doc?». E si capisce. E\' la frase «tormentone» del coniglio più famoso d\'America: Bugs Bunny. La faccia soddisfatta del dentone carota-dipendente la dice a ripetizione anche da noi, al di qua delle Alpi: «Che succede amico?». E non è un caso che sia proprio quella la frase la più famosa legata a un personaggio dei cartoon. Lo rivela un recente studio-sondaggio voluto dalla sede inglese del gruppo di distribuzione cinematografica Uci Cinemas per lanciare l\'ultimo film della Warner Bros, Back in Action. A 500 cinefili inglesi appassionati di cartoni animati è stato chiesto quale detto, frase o parola amano e ricordano di più in relazione a un cartoon. Bene: su tutti ha prevalso quel «what\'s up doc?», seguito da «Doh!», espressione fra lo sgomento e lo stupito di un personaggio ben più giovane di Bugs, Homer Simpson il confuso ispettore nucleare della famiglia più strampalata dei cartoon.'
		''
		'TEXT'
		''
		''
);

INSERT INTO post(id, autore,contenuto ,allegato, tipo, idGroup, idUser )
VALUES (default,
		'1'
		'
			"-Che c\'è, non hai mai sentito parlare di Google? Dovresti cercarlo su Google."
			"- A volte, non sempre ovviamente, ma a volte, io... vedo come delle cose. Ho delle visioni. Immagini distorte della realtà. [...] Oh, non è una cosa fissa. Ma il piccolo uomo pallido dietro la tenda, cioè il mio editor-- dice non più di due per episodio."
			"- Ehi, tamarro. Senti, io sono uno dei buoni--- be\', almeno in questo numero..." 
			"-Fare l\'eroe è la professione più breve del mondo. Fa tutto ridere, finchè capita a qualcun altro." 
			"- Sono stato creato specificamente dagli umani... per uccidere gli umani. Il che la dice lunga sulla razza umana in generale, non credete?!" 
			"- Una volta uno mi ha detto che alla fine di tutto rimpiangiamo non quello che abbiamo fatto, ma quello che non abbiamo fatto."
		'
		'img/pool.jpg'
		'IMAGE'
		''
		''
);

INSERT INTO post(id, autore,contenuto ,allegato, tipo, idGroup, idUser )
VALUES (default,
		'2'
		'La Ofcom ha spiegato che Tom & Jerry è un cartone animato vintage realizzato in un periodo in cui il rischio legato al fumo non era ancora stato attentamente studiato e che questa era un\'ottima ragione per chiedere alla Turner di prendere provvedimenti. Tom & Jerry però sono stati censurati altre volte. Molte scene di altri episodi contenevano dei blackface, cioè quando esplodeva qualcosa o il viso di Tom, Jerry o altri personaggi si coprivano di fango, essi diventavano come delle persone africane e ciò poteva risultare offensivo per le persone di origine africana. Un altro episodio censurato è Il suo topo Venerdì (His Mouse Friday, 1951) a causa degli stereotipi razziali in esso contenuti.'
		'https://i.makeagif.com/media/6-06-2015/nc_GSl.gif'
		'LINK'
		''
		''
);


/*
Inserimento delle iscrizioni
*/

INSERT INTO iscrizioni(idGruppi, idUtenti)
VALUES (0,0),
	   (0,2),
	   (1,1);



/*
Inserimento delle amicizie
*/

/*

AMICIZIE ......


*/

